[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
auto_detect_remappings = true
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
fuzz_runs = 1_000
#eth-rpc-url = "https://mainnet.infura.io"

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
optimism = "${OPTIMISM_GOERLI}"
arbitrum = "${ARBITRUM_GOERLI}"
mumbai = "${POLYGON_MUMBAI}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

[profile.ci]
fuzz_runs = 100_000
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
